web/router.ex
defmodule CoherenceDemo.Router do
  use CoherenceDemo.Web, :router
  use Coherence.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session
  end

  pipeline :protected do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session, protected: true
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/" do
    pipe_through :browser
    coherence_routes()
  end
  scope "/" do
    pipe_through :protected
    coherence_routes :protected
  end

  scope "/", CoherenceDemo do
    pipe_through :browser
    get "/", PageController, :index
  end

  scope "/", CoherenceDemo do
    pipe_through :protected
    resources "/posts", PostController
    resources "/users", UserController
    put "/lock/:id", UserController, :lock
    put "/unlock/:id", UserController, :unlock
    put "/confirm/:id", UserController, :confirm
  end

  # Other scopes may use custom stacks.
  # scope "/api", CoherenceDemo do
  #   pipe_through :api
  # end
end

web/models/coherence/user.ex
defmodule CoherenceDemo.User do
  @moduledoc false
  use Ecto.Schema
  use Coherence.Schema

  schema "users" do
    field :name, :string
    field :email, :string
    coherence_schema()

    timestamps()
  end

  def changeset(model, params \\ %{}) do
    model
    |> cast(params, [:name, :email] ++ coherence_fields())
    |> validate_required([:name, :email])
    |> validate_format(:email, ~r/@/)
    |> unique_constraint(:email)
    |> validate_coherence(params)
  end

  def changeset(model, params, :password) do
    model
    |> cast(params, ~w(password password_confirmation reset_password_token reset_password_sent_at))
    #|> validate_coherence_password_reset(params)
  end
end

web/views/coherence/coherence_view.ex
defmodule Coherence.CoherenceView do
  use CoherenceDemo.Coherence.Web, :view
end

web/views/coherence/confirmation_view.ex
defmodule Coherence.ConfirmationView do
  use CoherenceDemo.Coherence.Web, :view
end

web/views/coherence/email_view.ex
defmodule Coherence.EmailView do
  use CoherenceDemo.Coherence.Web, :view
end

web/views/coherence/invitation_view.ex
defmodule Coherence.InvitationView do
  use CoherenceDemo.Coherence.Web, :view
end

web/views/coherence/layout_view.ex
defmodule Coherence.LayoutView do
  use CoherenceDemo.Coherence.Web, :view
end

web/views/coherence/password_view.ex
defmodule Coherence.PasswordView do
  use CoherenceDemo.Coherence.Web, :view
end

web/views/coherence/registration_view.ex
defmodule Coherence.RegistrationView do
  use CoherenceDemo.Coherence.Web, :view
end

web/views/coherence/session_view.ex
defmodule Coherence.SessionView do
  use CoherenceDemo.Coherence.Web, :view
end

web/views/coherence/unlock_view.ex
defmodule Coherence.UnlockView do
  use CoherenceDemo.Coherence.Web, :view
end

web/templates/coherence/unlock/new.html.eex
<br \>

<%= form_for @conn, unlock_path(@conn, :create), [as: :unlock], fn f  -> %>

  <div class="form-group">
    <%= required_label f, dgettext("coherence", "Email"), class: "control-label" %>
    <%= text_input f, :email, class: "form-control", required: "" %>
    <%= error_tag f, :email %>
  </div>

  <div class="form-group">
    <%= required_label f, dgettext("coherence", "Password"), class: "control-label" %>
    <%= password_input f, :password, class: "form-control", required: "" %>
    <%= error_tag f, :password %>
  </div>

  <div class="form-group">
    <%= submit dgettext("coherence", "Send Instructions"), class: "btn btn-primary" %>
    <%= link dgettext("coherence", "Cancel"), to: Coherence.Config.logged_out_url("/"), class: "btn" %>
  </div>

<% end %>